name: Build LaTeX document added with PR
on: pull_request
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Remove template.tex
        run: "rm -f template.tex"
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "*.tex"
          pre_compile: "tlmgr update --self && tlmgr update --all && tlmgr install hyperref"
          glob_root_file: true
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: "*.pdf"
